/**********start.右侧面板**************/
//tabs切换面板
export const SET_TABSELECTED = 'SET_TABSELECTED';
//商店基本信息
export const SET_STOREINFO = 'SET_STOREINFO';
//控制右侧面板开关
export const SET_SWITCHPANEL = 'SET_SWITCHPANEL';

/**********end.右侧面板**************/

export const SWITCH_NEW_BRAND_MODAL = 'SWITCH_NEW_BRAND_MODAL'
export const SWITCH_BRAND_DETAIL_MODAL = 'SWITCH_BRAND_DETAIL_MODAL'
export const SWITCH_ADD_BRAND_MODAL = 'SWITCH_ADD_BRAND_MODAL'
// export const UPDATE_BRAND_SETTING_LIST = 'UPDATE_BRAND_SETTING_LIST'
// export const DELETE_BRAND_SETTING_LIST = 'DELETE_BRAND_SETTING_LIST'
export const CHANGE_BRAND_MODAL_STYLE = 'CHANGE_BRAND_MODAL_STYLE'
export const SET_CURRENT_BRAND_ID = 'SET_CURRENT_BRAND_ID'

/*************地图操作********************/
export const SETSWITCHSHOP = 'SETSWITCHSHOP'
export const SETSWITCHBRAND = 'SETSWITCHBRAND'
export const SETSWITCHHOT = 'SETSWITCHHOT'
export const SETSGRIDDINGMAPOVERLAYS = 'SETSGRIDDINGMAPOVERLAYS'
export const SETSHOPCOVER = 'SETSHOPCOVER'
export const SETBRANDCOVER = 'SETBRANDCOVER'
export const SETDROPDOWNSHOP = 'SETDROPDOWNSHOP'
export const SETCIRCLELINSTENER = 'SETCIRCLELINSTENER'
export const SETWALKLINSTENER = 'SETWALKLINSTENER'
export const SETDRIVELINSTENER = 'SETDRIVELINSTENER'
export const SETSELFMODAL = 'SETSELFMODAL'
export const SETCHECKBOXRANG = 'SETCHECKBOXRANG'
